# Generated by Django 4.0.4 on 2022-11-14 16:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_profile', models.ImageField(blank=True, default='media/bShop/temp/shablon.jpg', upload_to='media/lk/%Y/%m/%d/', verbose_name='фото профиля')),
                ('location', models.CharField(blank=True, default='ru', max_length=40, verbose_name='место раположения')),
                ('about', models.TextField(blank=True)),
                ('birthday', models.DateField(default=datetime.date.today)),
                ('city', models.CharField(blank=True, default='', max_length=15)),
                ('zodiac', models.CharField(blank=True, choices=[('', ''), ('Овен', 'Овен'), ('Телец', 'Телец'), ('Близнецы', 'Близнецы'), ('Рак', 'Рак'), ('Лев', 'Лев'), ('Дева', 'Дева'), ('Весы', 'Весы'), ('Скорпион', 'Скорпион'), ('Стрелец', 'Стрелец'), ('Козерог', 'Козерог'), ('Водолей', 'Водолей'), ('Рыбы', 'Рыбы')], default='', max_length=25)),
                ('socionics_type', models.CharField(blank=True, choices=[('', ''), ('Дюма', 'Дюма'), ('Гюго', 'Гюго'), ('Робеспьер', 'Робеспьер'), ('Гамлет', 'Гамлет'), ('Максим Горький', 'Максим Горький'), ('Жуков', 'Жуков'), ('Есенин', 'Есенин'), ('Наполеон', 'Наполеон'), ('Бальзак', 'Бальзак'), ('Джек Лондон', 'Джек Лондон'), ('Драйзер', 'Драйзер'), ('Штирлиц', 'Штирлиц'), ('Достоевский', 'Достоевский'), ('Гексли', 'Гексли'), ('Габен', 'Габен'), ('Дон Кихот', 'Дон Кихот')], default='', max_length=25)),
                ('show_profile', models.BooleanField(blank=True, default=True)),
                ('status', models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 14, 16, 19, 55, 321483, tzinfo=utc))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_friendshiop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='freanship', to='users.profiles')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='friend_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_type', models.CharField(blank=True, max_length=45)),
                ('profile_education', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='education', to='users.profiles')),
            ],
        ),
        migrations.CreateModel(
            name='Clas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clas', models.CharField(blank=True, max_length=4)),
                ('profile_class', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='clas', to='users.profiles')),
            ],
        ),
        migrations.CreateModel(
            name='AlbomsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='media/user/albomimage/%Y/%m/%d/')),
                ('profile_albomsimage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='albom', to='users.profiles')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
