# Generated by Django 4.0.4 on 2023-01-09 10:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clas',
            name='profile_class',
        ),
        migrations.AddField(
            model_name='profiles',
            name='profile_class',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='clas_num', to='users.clas'),
        ),
        migrations.AlterField(
            model_name='albomsimage',
            name='profile_albomsimage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albom', to='users.profiles'),
        ),
        migrations.AlterField(
            model_name='education',
            name='profile_education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='users.profiles'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='profile_friendshiop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freanship', to='users.profiles'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='status',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 9, 10, 28, 37, 443980)),
        ),
    ]
