# Generated by Django 4.0.4 on 2022-07-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albomsimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/user/albomimage/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='clas',
            name='clas',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
