# Generated by Django 4.0.4 on 2023-01-09 10:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_clas_profile_class_profiles_profile_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='profile_class',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='clas_num', to='users.clas'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='status',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 9, 10, 51, 48, 329575)),
        ),
    ]
