# Generated by Django 4.0.4 on 2023-01-09 10:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profiles_profile_class_alter_profiles_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clas',
            name='clas',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='profile_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clas_num', to='users.clas'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='status',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 9, 10, 53, 58, 172136)),
        ),
    ]
