# Generated by Django 4.0.4 on 2022-07-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profiles_albomimage_remove_profiles_clas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='socionics_type',
            field=models.CharField(blank=True, choices=[('0', ''), ('1', 'Дюма'), ('2', 'Гюго'), ('3', 'Робеспьер'), ('4', 'Гамлет'), ('5', 'Максим Горький'), ('6', 'Жуков'), ('7', 'Есенин'), ('8', 'Наполеон'), ('9', 'Бальзак'), ('10', 'Джек Лондон'), ('11', 'Драйзер'), ('12', 'Штирлиц'), ('13', 'Достоевский'), ('14', 'Гексли'), ('15', 'Габен'), ('16', 'Дон Кихот')], default='0', max_length=25),
        ),
        migrations.AddField(
            model_name='profiles',
            name='zodiac',
            field=models.CharField(blank=True, choices=[('0', ''), ('1', 'Овен'), ('2', 'Телец'), ('3', 'Близнецы'), ('4', 'Рак'), ('5', 'Лев'), ('6', 'Дева'), ('7', 'Весы'), ('8', 'Скорпион'), ('9', 'Стрелец'), ('10', 'Козерог'), ('11', 'Водолей'), ('12', 'Рыбы')], default='0', max_length=25),
        ),
    ]
