# Generated by Django 4.0.4 on 2022-07-29 08:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_profiles_socionics_type_profiles_zodiac'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albomsimage',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='albomsimage',
            name='profile_albomsimage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='albom', to='users.profiles'),
        ),
        migrations.AlterField(
            model_name='clas',
            name='profile_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='clas', to='users.profiles'),
        ),
        migrations.AlterField(
            model_name='education',
            name='profile_education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='education', to='users.profiles'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='profile_friendshiop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='freanship', to='users.profiles'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='friend_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='birthday',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='city',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='socionics_type',
            field=models.CharField(blank=True, choices=[('', ''), ('Дюма', 'Дюма'), ('Гюго', 'Гюго'), ('Робеспьер', 'Робеспьер'), ('Гамлет', 'Гамлет'), ('Максим Горький', 'Максим Горький'), ('Жуков', 'Жуков'), ('Есенин', 'Есенин'), ('Наполеон', 'Наполеон'), ('Бальзак', 'Бальзак'), ('Джек Лондон', 'Джек Лондон'), ('Драйзер', 'Драйзер'), ('Штирлиц', 'Штирлиц'), ('Достоевский', 'Достоевский'), ('Гексли', 'Гексли'), ('Габен', 'Габен'), ('Дон Кихот', 'Дон Кихот')], default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='zodiac',
            field=models.CharField(blank=True, choices=[('', ''), ('Овен', 'Овен'), ('Телец', 'Телец'), ('Близнецы', 'Близнецы'), ('Рак', 'Рак'), ('Лев', 'Лев'), ('Дева', 'Дева'), ('Весы', 'Весы'), ('Скорпион', 'Скорпион'), ('Стрелец', 'Стрелец'), ('Козерог', 'Козерог'), ('Водолей', 'Водолей'), ('Рыбы', 'Рыбы')], default='', max_length=25),
        ),
    ]
