# Generated by Django 4.0.4 on 2023-01-09 10:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_clas_clas_alter_profiles_profile_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='profile_class',
        ),
        migrations.AddField(
            model_name='clas',
            name='profile_class',
            field=models.ForeignKey(blank=True, default=10, on_delete=django.db.models.deletion.CASCADE, related_name='clas_num', to='users.profiles'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profiles',
            name='status',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 9, 10, 57, 59, 422401)),
        ),
    ]
