# Generated by Django 4.0.4 on 2022-10-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_albomsimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='show_profile',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
