# Generated by Django 4.0.4 on 2023-01-09 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_clas_profile_class_profiles_profile_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='status',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 9, 11, 21, 46, 810782)),
        ),
    ]
