# Generated by Django 4.0.4 on 2022-10-21 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profiles_show_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='status',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 21, 12, 58, 43, 656)),
        ),
    ]
