# Generated by Django 4.0.4 on 2023-01-09 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_clas_clas_alter_profiles_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='profile_class',
            field=models.CharField(blank=True, choices=[('', ''), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='status',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 9, 12, 45, 57, 923435)),
        ),
    ]
