# Generated by Django 4.0.4 on 2022-12-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscategorymodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/news/news_category/'),
        ),
        migrations.AlterField(
            model_name='postnewscategorymodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/news/posts/'),
        ),
    ]
