# Generated by Django 4.0.4 on 2022-11-14 16:19

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=40, verbose_name='название теста')),
                ('slug_quiz', models.SlugField(max_length=80, unique=True, verbose_name='ссылка на тест')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='QuizCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='имя категории')),
                ('slug', models.SlugField(max_length=80)),
                ('image', models.ImageField(blank=True, default='', upload_to='media/quiz/quiz_category/', verbose_name='фото категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='QuizKlass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='номер класса')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', picklefield.fields.PickledObjectField(editable=False)),
                ('question_number', models.CharField(max_length=20)),
                ('question_type', models.CharField(max_length=20)),
                ('student', models.CharField(max_length=30)),
                ('token', models.CharField(blank=True, default='0', max_length=1000)),
                ('result', models.CharField(max_length=1000)),
                ('quiz', picklefield.fields.PickledObjectField(editable=False)),
                ('result_fin', models.CharField(default='', max_length=100)),
                ('date_create', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='вопрос')),
                ('type_ege', models.IntegerField(blank=True, default=0)),
                ('category_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizes', to='quiz.quiz')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'вопросы',
            },
        ),
        migrations.CreateModel(
            name='QuizAnswerTrue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_true', models.CharField(max_length=1000, verbose_name='правильный ответ')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_true', to='quiz.quizcreate')),
            ],
            options={
                'verbose_name': 'Правильный ответ',
                'verbose_name_plural': 'Правильные ответы',
            },
        ),
        migrations.CreateModel(
            name='QuizAnswerFalse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_false', models.CharField(max_length=1000, verbose_name='ложный ответ')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_false', to='quiz.quizcreate')),
            ],
            options={
                'verbose_name': 'Ложный ответ',
                'verbose_name_plural': 'Ложные ответы',
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='category_quiz',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.quizcategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quizklass',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.quizklass', verbose_name='Класс'),
        ),
    ]
