# Generated by Django 4.0.4 on 2022-11-15 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizanswerfalse',
            old_name='quiz',
            new_name='quiz_false',
        ),
        migrations.RenameField(
            model_name='quizanswertrue',
            old_name='quiz',
            new_name='quiz_true',
        ),
    ]
