# Generated by Django 4.0.4 on 2022-11-14 16:20

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Категория')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, default='media/bShop/temp/shablon.jpg', upload_to='media/bShop/%Y/%m/%d/', verbose_name='Изображение')),
                ('url', models.SlugField(max_length=1200, verbose_name='Ссылка')),
            ],
            options={
                'db_table': 'bShop_category',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyitem', models.CharField(blank=True, default='0', max_length=1000, verbose_name='Код товара')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование товара')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('price', models.IntegerField(blank=True, default=100, verbose_name='Цена')),
                ('skidka', models.BooleanField(blank=True, default=False, verbose_name='Скида')),
                ('count', models.IntegerField(blank=True, default=0, verbose_name='Кол=во')),
                ('url', models.SlugField(max_length=266)),
                ('image', models.ImageField(upload_to='media/bShop/Item/%Y/%m/%d/', verbose_name='Главное фото')),
            ],
            options={
                'db_table': 'bShop_item',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Производитель')),
                ('contry', models.CharField(max_length=1000, verbose_name='Страна')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Подкатегория')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, default='media/bShop/temp/shablon.jpg', upload_to='media/bShop/%Y/%m/%d/', verbose_name='Изображение')),
                ('slug', models.SlugField(max_length=1200, verbose_name='Ссылка')),
                ('category', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category')),
            ],
            options={
                'db_table': 'bShop_subcategory',
            },
        ),
        migrations.CreateModel(
            name='ReviewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.items')),
            ],
            options={
                'db_table': 'bShop_reviewsitem',
            },
        ),
        migrations.AddField(
            model_name='items',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.model'),
        ),
        migrations.AddField(
            model_name='items',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.subcategory'),
        ),
        migrations.CreateModel(
            name='ImageItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='media/bShop/Item/%Y/%m/%d/', verbose_name='Главное фото')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.items')),
            ],
            options={
                'db_table': 'bShop_imageitems',
            },
        ),
    ]
