# Generated by Django 4.0.4 on 2022-06-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='slugs',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(default=1, max_length=1200, verbose_name='Ссылка'),
            preserve_default=False,
        ),
    ]
