# Generated by Django 4.0.4 on 2022-09-10 15:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('privatmessages', '0002_message_chat_alter_message_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 10, 15, 20, 38, 41874, tzinfo=utc)),
        ),
    ]
