# Generated by Django 4.0.4 on 2022-10-21 09:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('privatmessages', '0005_alter_message_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 21, 9, 58, 44, 225329, tzinfo=utc)),
        ),
    ]
